<div class="w-screen h-screen flex flex-col justify-center items-center">
    <div class="search p-3">
        <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 paid"><?php echo $t->_('paid'); ?></button>
        <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 processing"><?php echo $t->_('processing'); ?></button>
        <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 dispatched"><?php echo $t->_('dispatched'); ?></button>
        <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 shipped"><?php echo $t->_('shipped'); ?></button>
        <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 refunded"><?php echo $t->_('refunded'); ?></button>
        <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 today"><?php echo $t->_('today'); ?></button>
        <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 this_week"><?php echo $t->_('this week'); ?></button>
        <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 this_month"><?php echo $t->_('this month'); ?></button>
        <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 custom"><?php echo $t->_('custom'); ?></button>
        <a href="/orders/">
            <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 clear"><?php echo $t->_('clear'); ?></button>
        </a>
    </div>
    <div class="date p-3 hidden">
        <input type="text" class="rounded-lg shadow-md border-gray-200 mr-2 from_date" placeholder="from date (dd-mm-YY)" name="" id="">
        <input type="text" class="rounded-lg shadow-md border-gray-200 mr-2 to_date" placeholder="to date  (dd-mm-YY)" name="" id="">
        <button class="mr-2 px-3 py-2 border rounded-lg shadow-md capitalize hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300 searchCustom"><?php echo $t->_('search'); ?></button>
    </div>
    <table>
        <thead>
            <th class="p-3 border"><?php echo $t->_('customer name'); ?></th>
            <th class="p-3 border"><?php echo $t->_('quantity'); ?></th>
            <th class="p-3 border"><?php echo $t->_('product'); ?></th>
            <th class="p-3 border"><?php echo $t->_('varient'); ?></th>
            <th class="p-3 border"><?php echo $t->_('status'); ?></th>
            <th class="p-3 border"><?php echo $t->_('order date'); ?></th>
        </thead>
        <tbody class="tbody">
            <?php
            foreach ($data as $doc) {
            ?>
                <tr class="text-center">
                    <td class="p-3 border"><?php echo $doc["customer name"] ?></td>
                    <td class="p-3 border"><?php echo $doc["quantity"] ?></td>
                    <td class="p-3 border"><?php echo $doc["productId"] ?></td>
                    <td class="p-3 border"><?php echo $doc["varient"] ?></td>
                    <td class="p-3 border">
                        <select class="rounded-lg shadow-md border-gray-200 status" data="<?php echo $doc["_id"] ?>" name="status" id="">
                            <option value="paid" <?php echo $doc["status"] == "paid" ? "selected" : "" ?>>paid</option>
                            <option value="processing" <?php echo $doc["status"] == "processing" ? "selected" : "" ?>>processing</option>
                            <option value="dispatched" <?php echo $doc["status"] == "dispatched" ? "selected" : "" ?>>dispatched</option>
                            <option value="shipped" <?php echo $doc["status"] == "shipped" ? "selected" : "" ?>>shipped</option>
                            <option value="refunded" <?php echo $doc["status"] == "refunded" ? "selected" : "" ?>>refunded</option>
                        </select>
                    </td>
                    <td class="p-3 border"><?php echo date("d-m-Y", (string) $doc["order date"]) ?></td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>
<?php
$this->assets->outputJs();
?>