<div class="w-screen h-screen bg-gray-100 flex items-center justify-center">
    <form action="/signup" method="post" class="flex flex-col text-gray-700">
        <div class="text-6xl text-center text-blue-600">
            <ion-icon name="camera-reverse" class="drop-shadow-lg"></ion-icon>
        </div>
        <label for="name">
            <p>Name</p>
            <input type="text" class="rounded-md border-gray-200 shadow-sm text-gray-800" name="name" id="name" >
        </label>
        <label for="email">
            <p class="mt-2">Email</p>
            <input type="email" class="rounded-md border-gray-200 shadow-sm text-gray-800" name="email" id="email" >
        </label>
        <label for="password">
            <p class="mt-2">Password</p>
            <input type="text" class="rounded-md border-gray-200 shadow-sm text-gray-800" name="password" id="password" >
        </label>
        <label for="submit">
            <button class="text-white bg-blue-600 w-full mt-4 p-2.5 hover:ring-2 hover:ring-offset-2 rounded-md shadow-sm">Register</button>
        </label>
    </form>
</div>